# -*- coding: utf-8 -*-
"""spatial_sdm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mai5YWzbiDMfp4wc-jCXWN69tH_k1OuR
"""

import numpy as np
import pandas as pd
import pymc as pm
import pytensor.tensor as pt

def run_sdm_model(df_sorted, W_cul06, draws=2000, tune=2000):
    """
    Fit a Spatial Durbin Model (SDM) in PyMC using panel data.

    Parameters
    ----------
    df_sorted : pd.DataFrame
        Panel data sorted by ['year', 'country'] with columns:
        ['GDP', 'Political Stability', 'exchange rate', 'Rule of Law: Estimate', 'inbound']
    W_cul06 : pd.DataFrame
        Base spatial weight matrix (NxN) with countries as index/columns
    draws : int
        Number of posterior draws
    tune : int
        Number of tuning steps

    Returns
    -------
    trace : arviz.InferenceData
        Posterior samples
    """
    # --- Ensure year column is int ---
    df_sorted['year'] = df_sorted['year'].astype(int)

    # --- Panel indices ---
    years_sorted = sorted(df_sorted['year'].unique())
    countries_sorted = sorted(df_sorted['country'].unique())
    T = len(years_sorted)
    N = len(countries_sorted)

    country_to_idx = {c: i for i, c in enumerate(countries_sorted)}
    year_to_idx = {yr: i for i, yr in enumerate(years_sorted)}

    country_idx = df_sorted['country'].map(country_to_idx).to_numpy(dtype="int32")
    year_idx = df_sorted['year'].map(year_to_idx).to_numpy(dtype="int32")

    # --- Covariates and dependent variable ---
    X = df_sorted[['GDP', 'Political Stability', 'exchange rate', "Rule of Law: Estimate"]].to_numpy(dtype="float64")
    y = df_sorted['inbound'].to_numpy(dtype="float64")
    K = X.shape[1]
    NT = X.shape[0]

    # --- Build W_dict for all years using same W_cul06 ---
    W_base = W_cul06.values.astype("float64")
    assert W_base.shape == (N, N), "W_base must be NxN"

    # Row-standardize
    row_sums = W_base.sum(axis=1)
    W_rs = W_base.copy()
    nonzero = row_sums != 0
    W_rs[nonzero, :] = W_base[nonzero, :] / row_sums[nonzero][:, None]
    W_base = W_rs

    # W_dict mapping int year -> W_base
    W_dict = {year: W_base for year in years_sorted}

    # Eigenvalues
    eig_base = np.linalg.eigvals(W_base).real
    max_abs_eig = float(np.max(np.abs(eig_base)))

    # --- Construct WX ---
    WX = np.zeros((NT, K), dtype="float64")
    for t_idx in range(T):
        X_t = X[t_idx * N:(t_idx + 1) * N, :]
        WX_t = W_base @ X_t
        WX[t_idx * N:(t_idx + 1) * N, :] = WX_t

    # --- PyMC model ---
    with pm.Model() as sdm_model:
        # Data
        X_data = pm.Data("X", X)
        WX_data = pm.Data("WX", WX)
        y_data = pm.Data("y", y)
        country_idx_data = pm.Data("country_idx", country_idx)
        year_idx_data = pm.Data("year_idx", year_idx)
        W_base_data = pm.Data("W_base", W_base)
        eig_base_data = pm.Data("eig_base", eig_base)

        # Coefficients
        beta = pm.Normal("beta", mu=0.0, sigma=5.0, shape=K)
        gamma = pm.Normal("gamma", mu=0.0, sigma=5.0, shape=K)

        # Country effects
        mu_alpha = pm.Normal("mu_alpha", mu=0.0, sigma=2.0)
        sigma_alpha = pm.HalfNormal("sigma_alpha", sigma=2.0)
        alpha_raw = pm.Normal("alpha_raw", mu=0.0, sigma=1.0, shape=N)
        alpha = pm.Deterministic("alpha", mu_alpha + sigma_alpha * alpha_raw)

        # Time effects
        time_alpha_raw = pm.Normal("time_alpha_raw", mu=0.0, sigma=1.0, shape=T)
        time_alpha = pm.Deterministic("time_alpha", time_alpha_raw * 2.0)

        # Rho
        eta = pm.Normal("eta", mu=0.0, sigma=1.0)
        rho = pm.Deterministic("rho", 0.95 * pt.tanh(eta))

        # Residual sigma
        sigma = pm.HalfNormal("sigma", sigma=2.0)

        # Linear predictor
        XB = pt.dot(X_data, beta) + pt.dot(WX_data, gamma) + alpha[country_idx_data] + time_alpha[year_idx_data]

        # Efficient Ay = (I - rho*W) y
        y_matrix = pt.reshape(y_data, (T, N))
        I_N = pt.eye(N)
        A_base = I_N - rho * W_base_data
        Ay_matrix = pt.dot(y_matrix, A_base.T)
        Ay = pt.reshape(Ay_matrix, (T * N,))

        # Residuals
        eps = Ay - XB

        # Log-likelihood
        log_det = T * pt.sum(pt.log(1.0 - rho * eig_base_data + 0.0))
        ll_const = -0.5 * NT * pt.log(2.0 * np.pi * sigma**2)
        ll_quad = -0.5 * pt.sum(eps**2) / (sigma**2)
        log_like = ll_const + ll_quad + log_det
        pm.Potential("sdm_loglik", log_like)

        # Stability penalty
        penalty = pt.switch(pt.lt(pt.abs(rho) * max_abs_eig, 0.9999), 0.0, -1.0e6)
        pm.Potential("stability_penalty", penalty)

        # Sampling
        trace = pm.sample(
            draws=draws,
            tune=tune,
            chains=4,
            target_accept=0.95,
            max_treedepth=15,
            return_inferencedata=True
        )

    return trace

import arviz as az
import pandas as pd

def summarize_sdm_trace(trace, countries_sorted, years_sorted, round_to=4):
    """
    Summarize posterior results from SDM model.

    Parameters
    ----------
    trace : arviz.InferenceData
        Posterior samples from run_sdm_model
    countries_sorted : list
        List of country names in panel order
    years_sorted : list
        List of years in panel order
    round_to : int
        Number of decimals to round main coefficients summary

    Returns
    -------
    summary_main : pd.DataFrame
        Summary of main coefficients: rho, beta, gamma, sigma
    df_alpha : pd.DataFrame
        Posterior mean and SD of country fixed effects
    df_time_alpha : pd.DataFrame
        Posterior mean and SD of time fixed effects
    """
    # --- 1) Summary of main coefficients ---
    summary_main = az.summary(trace, var_names=["rho", "beta", "gamma", "sigma"], round_to=round_to)
    print("Main coefficients summary:\n", summary_main)

    # --- 2) Hierarchical country and time fixed effects ---
    alpha_post = trace.posterior["alpha"]  # dims: chain x draw x N
    alpha_mean = alpha_post.mean(dim=("chain", "draw")).values
    alpha_sd = alpha_post.std(dim=("chain", "draw")).values

    time_alpha_post = trace.posterior["time_alpha"]
    time_alpha_mean = time_alpha_post.mean(dim=("chain", "draw")).values
    time_alpha_sd = time_alpha_post.std(dim=("chain", "draw")).values

    df_alpha = pd.DataFrame({
        "country": countries_sorted,
        "alpha_mean": alpha_mean,
        "alpha_sd": alpha_sd
    })

    df_time_alpha = pd.DataFrame({
        "year": years_sorted,
        "time_alpha_mean": time_alpha_mean,
        "time_alpha_sd": time_alpha_sd
    })

    print("\nCountry fixed effects (alpha) posterior summary:\n", df_alpha)
    print("\nTime fixed effects (time_alpha) posterior summary:\n", df_time_alpha)

    return summary_main, df_alpha, df_time_alpha

import numpy as np

def compute_sdm_effects(trace, W_base):
    """
    Compute Direct, Indirect, and Total effects for SDM model.

    Parameters
    ----------
    trace : arviz.InferenceData
        Posterior samples from run_sdm_model
    W_base : np.ndarray
        Base spatial weight matrix (NxN), row-standardized

    Returns
    -------
    DE : np.ndarray
        Direct effects for each covariate
    IE : np.ndarray
        Indirect effects (spillovers) for each covariate
    TE : np.ndarray
        Total effects for each covariate
    """
    # --- Extract mean posterior values ---
    rho_mean = trace.posterior["rho"].mean(dim=("chain","draw")).item()  # scalar
    beta_mean = trace.posterior["beta"].mean(dim=("chain","draw")).values  # array
    gamma_mean = trace.posterior["gamma"].mean(dim=("chain","draw")).values  # array

    # Spatial multiplier matrix
    N = W_base.shape[0]
    S = np.linalg.inv(np.eye(N) - rho_mean * W_base)

    # Initialize lists
    DE = []
    IE = []
    TE = []

    # Compute effects for each covariate
    for k in range(len(beta_mean)):
        A_k = beta_mean[k] * np.eye(N) + gamma_mean[k] * W_base
        total_effect_mat = S @ A_k
        direct_effect = np.trace(total_effect_mat) / N
        total_effect = total_effect_mat.sum() / N
        indirect_effect = total_effect - direct_effect

        DE.append(direct_effect)
        IE.append(indirect_effect)
        TE.append(total_effect)

    DE = np.array(DE)
    IE = np.array(IE)
    TE = np.array(TE)

    print("Direct effects:", DE)
    print("Indirect effects:", IE)
    print("Total effects:", TE)

    return DE, IE, TE

def compute_sdm_predictions(trace, X, WX, country_idx, year_idx, W_base, countries_sorted, y):
    """
    Compute posterior predictive values and MSE by country for SDM model.

    Parameters
    ----------
    trace : arviz.InferenceData
        Posterior samples from run_sdm_model
    X : np.ndarray
        Covariates matrix (NT x K)
    WX : np.ndarray
        Spatially lagged covariates (NT x K)
    country_idx : np.ndarray
        Country indices for each observation (NT,)
    year_idx : np.ndarray
        Year indices for each observation (NT,)
    W_base : np.ndarray
        Base spatial weight matrix (N x N), row-standardized
    countries_sorted : list
        List of country names in panel order
    y : np.ndarray
        Actual dependent variable (NT,)

    Returns
    -------
    y_pred_mean : np.ndarray
        Posterior mean predictions (NT,)
    mse_by_country : dict
        Mean squared error for each country
    """
    posterior = trace.posterior
    N = W_base.shape[0]
    T = len(np.unique(year_idx))

    n_draws = posterior.sizes["draw"] * posterior.sizes["chain"]

    beta_samples = posterior["beta"].stack(draws=("chain", "draw")).values
    gamma_samples = posterior["gamma"].stack(draws=("chain", "draw")).values
    alpha_samples = posterior["alpha"].stack(draws=("chain", "draw")).values
    time_alpha_samples = posterior["time_alpha"].stack(draws=("chain", "draw")).values
    rho_samples = posterior["rho"].stack(draws=("chain", "draw")).values

    y_pred_samples = np.zeros((n_draws, X.shape[0]))

    for s in range(n_draws):
        beta_s = beta_samples[:, s]
        gamma_s = gamma_samples[:, s]
        alpha_s = alpha_samples[:, s]
        time_s = time_alpha_samples[:, s]
        rho_s = rho_samples[s]

        XB = X @ beta_s + WX @ gamma_s + alpha_s[country_idx] + time_s[year_idx]
        S = np.linalg.inv(np.eye(N) - rho_s * W_base)
        y_pred = np.zeros(X.shape[0])
        for t in range(T):
            y_pred[t*N:(t+1)*N] = S @ XB[t*N:(t+1)*N]
        y_pred_samples[s, :] = y_pred

    y_pred_mean = y_pred_samples.mean(axis=0)

    mse_by_country = {}
    for c_idx, country in enumerate(countries_sorted):
        mask = country_idx == c_idx
        mse_by_country[country] = np.mean((y[mask] - y_pred_mean[mask])**2)

    return y_pred_mean, mse_by_country

import numpy as np
from libpysal.weights import W
from esda.moran import Moran

def compute_morans_i(y, X, WX, beta_mean, gamma_mean, alpha_mean, time_alpha_mean,
                     rho_mean, W_base, country_idx, year_idx, N, T):
    """
    Compute Moran's I for SDM residuals for each year.

    Parameters
    ----------
    y : np.ndarray
        Observed dependent variable (NT,)
    X : np.ndarray
        Covariates matrix (NT x K)
    WX : np.ndarray
        Spatially lagged covariates (NT x K)
    beta_mean : np.ndarray
        Posterior mean of beta (K,)
    gamma_mean : np.ndarray
        Posterior mean of gamma (K,)
    alpha_mean : np.ndarray
        Posterior mean of country fixed effects (N,)
    time_alpha_mean : np.ndarray
        Posterior mean of time fixed effects (T,)
    rho_mean : float
        Posterior mean of rho
    W_base : np.ndarray
        Base spatial weight matrix (N x N)
    country_idx : np.ndarray
        Country indices (NT,)
    year_idx : np.ndarray
        Year indices (NT,)
    N : int
        Number of countries
    T : int
        Number of years

    Returns
    -------
    morans_i : list
        Moran's I statistic for each year
    """
    # --- Create PySAL W object ---
    neighbors = {i: list(np.where(W_base[i] > 0)[0]) for i in range(N)}
    weights = {i: W_base[i, neighbors[i]] for i in range(N)}
    W_pysal = W(neighbors, weights)

    # --- Compute linear predictor ---
    XB = (X @ beta_mean) + (WX @ gamma_mean) + alpha_mean[country_idx] + time_alpha_mean[year_idx]

    # --- Residuals adjusted for spatial lag ---
    y_resid = np.zeros_like(y)
    for t_idx in range(T):
        y_t = y[t_idx*N:(t_idx+1)*N]
        XB_t = XB[t_idx*N:(t_idx+1)*N]
        y_resid[t_idx*N:(t_idx+1)*N] = y_t - rho_mean * (W_base @ y_t) - XB_t

    # --- Moran's I for each year ---
    morans_i = []
    for t_idx in range(T):
        y_resid_t = y_resid[t_idx*N:(t_idx+1)*N]
        mi = Moran(y_resid_t, W_pysal)
        morans_i.append(mi.I)

    print("Moran's I by year:", morans_i)

    return morans_i